services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672